apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  project: default
  source:
    chart: descheduler
    repoURL: https://kubernetes-sigs.github.io/descheduler/
    targetRevision: 0.26.1
    helm:
      releaseName: descheduler
      # parameters:
      #   - name: "deschedulerPolicy.LowNodeUtilization.enabled"
      #     value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: descheduler
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
