apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx-ingress
    repoURL: https://helm.nginx.com/stable
    targetRevision: 0.17.0
    helm:
      releaseName: nginx-ingress
      parameters:
        - name: "controller.type"
          value: DaemonSet
        - name: "controller.watchIngressWithoutClass"
          value: "true"
        - name: "controller.ingressClassResource.default"
          value: "true"
        - name: "controller.service.externalTrafficPolicy"
          value: Local
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
