apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx-ingress
    repoURL: https://helm.nginx.com/stable
    targetRevision: 0.15.2
    helm:
      releaseName: nginx-ingress
      parameters:
        - name: "controller.type"
          value: DaemonSet
        - name: "controller.watchIngressWithoutClass"
          value: true
        - name: "controller.ingressClassResource.default"
          value: true
        - name: "controller.service.externalTrafficPolicy"
          value: Local
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx-ingress